# Generated by Django 4.2.18 on 2025-02-11 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('liveapp', '0002_blogpost_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_four',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_three',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_two',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
