# Generated by Django 4.2.18 on 2025-03-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveapp', '0004_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image_four',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image_three',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image_two',
        ),
    ]
